### ISSUE TITLE
To:Gitコマンド備忘録

### ISSUE THREAD

**Issue by matopenKW** [whitealcea/TIL#2]
Windowsで pushする際に 正しくbranch  の指定ができていな場合があり
一度、pull した上でpushしたらできた。
備忘録

**Comment by whitealcea** [comment]
ローカルとリモートに差異がある場合は、一度ローカル環境を最新にするためにpullをしてからpushするというのはわかる。
その際に出るエラーメッセージが何だったかは忘れた。
エラー対処として別文書に記載しようと思います。

**Comment by matopenKW** [comment]
なるほど、勉強になります。

**Comment by whitealcea** [comment]
まだ修正していないのでReopenします。
修正確認したらCloseしてください
対応忘れてしまうので……

**Comment by matopenKW** [comment]
了解です。
ごめんなさい、まだ慣れていないもので…

**Comment by matopenKW** [comment]
確認しました。
以降はまた別の課題があがったら、別課題として質問します。
